[project]
name = 'stacks-based-stablecoin'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.stacks-based-stablecoin]
path = 'contracts/stacks-based-stablecoin.clar'
clarity_version = 3
epoch = 3.0

[contracts.stx-price-feed]
path = 'contracts/stx-price-feed.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
